name: g_livres
description: A Flutter book application
version: 1.0.0+1

environment:
  sdk: '^3.7.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.3 # Add this line for desktop support
  path: ^1.9.1
  cached_network_image: ^3.4.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
